#!/bin/bash
export TERM=screen-256color
alias reload="source ~/.bashrc"
alias tmux-work="~/workspace/dotfiles/tmux/tmux-work.sh"
alias +='pushd .'
alias -- -='popd'

login() {
  already_logged_in=`ssh-add -l | grep RSA | wc -l`
  if [ "$already_logged_in" -eq "0" ]; then
      eval `ssh-agent`
      ssh-add
  fi
}
