#!/bin/bash
export TERM=screen-256color
alias reload="source ~/.bashrc"
alias tmux-work="~/workspace/dotfiles/tmux/tmux-work.sh"
alias +='pushd .'
alias -- -='popd'
alias nyan="nc -v miku.acm.uiuc.edu 23"

login() {
  already_logged_in=`ssh-add -l | grep RSA | wc -l`
  if [ "$already_logged_in" -eq "0" ]; then
      eval `ssh-agent`
      ssh-add
  fi
}

###
# jump aliases, courtesy Jeroen Janssens:
# http://jeroenjanssens.com/2013/08/16/quickly-navigate-your-filesystem-from-the-command-line.html
###
export MARKPATH=$HOME/.marks
function jump {
    cd -P "$MARKPATH/$1" 2>/dev/null || echo "No such mark: $1"
}
function mark {
    mkdir -p "$MARKPATH"; ln -s "$(pwd)" "$MARKPATH/$1"
}
function unmark {
    rm -i "$MARKPATH/$1"
}
function marks {
    mkdir -p "$MARKPATH"
    ls -l "$MARKPATH" | sed 's/  / /g' | cut -d' ' -f9- | sed 's/ -/\t-/g' && echo
}
_completemarks() {
    local curw=${COMP_WORDS[COMP_CWORD]}
    local wordlist=$(find $MARKPATH -type l -printf "%f\n")
    COMPREPLY=($(compgen -W '${wordlist[@]}' -- "$curw"))
    return 0
}
complete -F _completemarks jump unmark
