#!/bin/bash
export TERM=screen-256color
alias reload="source ~/.bashrc"
alias tmux-irc="~/workspace/dotfiles/tmux/tmux-irc.sh"
alias tmux-work="~/workspace/dotfiles/tmux/tmux-work.sh"
alias +='pushd .'
alias -- -='popd'
alias nyan="nc -v miku.acm.uiuc.edu 23"

export CLICOLOR=1
export LSCOLORS=ExFxBxDxCxegedabagacad

login() {
  already_logged_in=`ssh-add -l | grep RSA | wc -l`
  if [ "$already_logged_in" -eq "0" ]; then
      eval `ssh-agent`
      ssh-add
  fi
}

###
# jump aliases, courtesy Jeroen Janssens:
# http://jeroenjanssens.com/2013/08/16/quickly-navigate-your-filesystem-from-the-command-line.html
###
export MARKPATH=$HOME/.marks
function jump {
    if [ "$1" == "" ]; then
        echo "Please specify a mark"
        return 1
    fi
    cd -P "$MARKPATH/$1" 2>/dev/null || echo "No such mark: $1"
}
function mark {
    mkdir -p "$MARKPATH"; ln -sf "$(pwd)" "$MARKPATH/$1"
}
function unmark {
    rm -i "$MARKPATH/$1"
}
function marks {
    mkdir -p "$MARKPATH"
    ls -l "$MARKPATH" | sed 's/\s\s*/ /g' | cut -d' ' -f9- | sed 's/ -/\t-/g' && echo
}
_completemarks() {
    local curw=${COMP_WORDS[COMP_CWORD]}
    local wordlist=$(find $MARKPATH -type l -printf "%f\n")
    COMPREPLY=($(compgen -W '${wordlist[@]}' -- "$curw"))
    return 0
}
if [ "$(uname)" == "Darwin" ]; then
    function marks {
        \ls -l "$MARKPATH" | tail -n +2 | sed 's/  / /g' | cut -d' ' -f9- | awk -F ' -> ' '{printf "%-10s -> %s\n", $1, $2}'
    }
    _completemarks() {
        local curw=${COMP_WORDS[COMP_CWORD]}
        local wordlist=$(find $MARKPATH -type l | xargs -n1 basename)
        COMPREPLY=($(compgen -W '${wordlist[@]}' -- "$curw"))
        return 0
    }
fi
complete -F _completemarks jump unmark
alias j="jump"
